---
controller_inventory_sources:
  - name: demo_inventory
    organization: Default
    source: scm
    source_project: demo_inventory_project
    source_path: inventory.yml
    inventory: demo_inventory
  - name: demo_inventory_aws
    organization: Default
    source: ec2
    credential: aws
    source_vars:
      hostnames:
        - tag:Name
        - tag:CustomDNSName
...
