---
- name: Demo rules with kafka as source
  hosts: localhost
  sources:
    - name: listen for kafka
      ansible.eda.kafka:
        topic: FirstKafkaTopic
        host: ah.aap24.local
        port: 9092

  rules:
    - name: Check defined
      action:
        debug:
